#!/usr/bin/env python3
os.environ["TZ"] = "America/St_Johns"
import time
time.tzset()
"""
Claw Code Generator
Generates boilerplate for common tool patterns
"""

import os
import sys
from datetime import datetime

TEMPLATES = {
    "cli_tool": '''#!/usr/bin/env python3
"""
{title}
{description}
"""

import argparse
import json
import os
from datetime import datetime

LOG_FILE = "/config/clawd/memory/{name}_log.jsonl"

def log_event(action, status, details=""):
    """Log operation"""
    entry = {{
        "timestamp": datetime.now().isoformat(),
        "action": action,
        "status": status,
        "details": details
    }}
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
    with open(LOG_FILE, 'a') as f:
        f.write(json.dumps(entry) + '\\n')

def main():
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()
    
    print("🦅 {title}")
    print("=" * 40)
    
    # Your code here
    
    log_event("run", "success")
    print("✓ Done!")

if __name__ == "__main__":
    main()
''',

    "cron_job": '''#!/usr/bin/env python3
"""
{title} - Cron Job Script
{description}
"""

import json
import os
from datetime import datetime

LOG_FILE = "/config/clawd/memory/{name}_log.jsonl"

def main():
    """Main cron job function"""
    timestamp = datetime.now().isoformat()
    
    # Your scheduled task here
    result = "Task completed"
    
    # Log result
    entry = {{
        "timestamp": timestamp,
        "job": "{name}",
        "result": result,
        "status": "success"
    }}
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
    with open(LOG_FILE, 'a') as f:
        f.write(json.dumps(entry) + '\\n')
    
    return result

if __name__ == "__main__":
    result = main()
    print(f"🦅 {{result}}")
''',

    "monitor": '''#!/usr/bin/env python3
"""
{title}
{description}
"""

import json
import os
import subprocess
from datetime import datetime

LOG_FILE = "/config/clawd/memory/{name}_log.jsonl"
ALERT_THRESHOLD = 3  # Alert after N consecutive failures

def check_service():
    """Check the service status"""
    try:
        # Add your check logic here
        result = subprocess.run(["echo", "ok"], capture_output=True, text=True)
        return result.returncode == 0
    except:
        return False

def log_check(status, details=""):
    """Log check result"""
    entry = {{
        "timestamp": datetime.now().isoformat(),
        "check": "{name}",
        "status": "up" if status else "down",
        "details": details
    }}
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
    with open(LOG_FILE, 'a') as f:
        f.write(json.dumps(entry) + '\\n')

def main():
    print("🔍 {title}")
    
    is_healthy = check_service()
    log_check(is_healthy)
    
    if is_healthy:
        print("✅ Service is healthy")
    else:
        print("❌ Service check failed")
        # Add alerting logic here
    
    return is_healthy

if __name__ == "__main__":
    main()
''',

    "web_dashboard": '''<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eaeaea;
            padding: 2rem;
            max-width: 1200px;
            margin: 0 auto;
        }}
        h1 {{ color: #667eea; }}
        .card {{
            background: rgba(255,255,255,0.05);
            padding: 1.5rem;
            border-radius: 12px;
            margin: 1rem 0;
            border: 1px solid rgba(255,255,255,0.1);
        }}
    </style>
</head>
<body>
    <h1>🦅 {title}</h1>
    
    <div class="card">
        <h2>Status</h2>
        <p>Replace with live data</p>
    </div>
    
    <footer>
        <p style="color: #666;">Generated by Claw 🦅</p>
    </footer>
    
    <script>
        // Add JavaScript here
    </script>
</body>
</html>
''',
}

def generate(name, template_type, title=None, description=None):
    """Generate code from template"""
    
    if template_type not in TEMPLATES:
        print(f"❌ Unknown template: {template_type}")
        print(f"Available: {', '.join(TEMPLATES.keys())}")
        return None
    
    # Defaults
    title = title or name.replace("_", " ").title()
    description = description or f"Tool: {name}"
    
    # Fill template
    template = TEMPLATES[template_type]
    code = template.format(
        name=name,
        title=title,
        description=description
    )
    
    return code

def main():
    print("🦅 Claw Code Generator")
    print("=" * 50)
    
    if len(sys.argv) < 3:
        print("\nUsage:")
        print(f"  {sys.argv[0]} <name> <template> [title] [description]")
        print("\nTemplates:")
        for t in TEMPLATES.keys():
            print(f"  • {t}")
        print("\nExamples:")
        print(f"  {sys.argv[0]} my_tool cli_tool 'My Tool' 'Does something cool'")
        print(f"  {sys.argv[0]} daily_check cron_job 'Daily Check' 'Runs every day'")
        sys.exit(1)
    
    name = sys.argv[1]
    template_type = sys.argv[2]
    title = sys.argv[3] if len(sys.argv) > 3 else None
    description = sys.argv[4] if len(sys.argv) > 4 else None
    
    # Generate
    code = generate(name, template_type, title, description)
    
    if code:
        # Determine output path
        if template_type == "web_dashboard":
            output_path = f"/config/clawd/dashboard/public/{name}.html"
        else:
            output_path = f"/config/clawd/tools/{name}.py"
        
        # Check if exists
        if os.path.exists(output_path):
            print(f"⚠️  File exists: {output_path}")
            response = input("Overwrite? (y/N): ")
            if response.lower() != 'y':
                print("Cancelled.")
                sys.exit(0)
        
        # Write
        with open(output_path, 'w') as f:
            f.write(code)
        
        # Make executable if Python
        if output_path.endswith('.py'):
            os.chmod(output_path, 0o755)
        
        print(f"✅ Generated: {output_path}")
        print(f"   Template: {template_type}")
        print(f"   Lines: {len(code.split(chr(10)))}")
        
        # Next steps
        print("\n📝 Next steps:")
        print(f"   1. Edit {output_path}")
        print(f"   2. Test: python3 {output_path}")
        print(f"   3. Add to git and commit")

if __name__ == "__main__":
    main()
